[package]
name = "dhruv_cli"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
dhruv_vedic_base = { path = "../dhruv_vedic_base" }
clap = { version = "4", features = ["derive"] }
