[package]
name = "eph_ffi_c"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
eph_core = { path = "../eph_core" }
eph_time = { path = "../eph_time" }
eph_frames = { path = "../eph_frames" }
